server:
  port: 8120
# 数据库
spring:
  redis:
    host: 192.168.43.128
    port: 6379
    database: 0
#    password: 123456
#    timeout: 3000ms
#    lettuce:
#      pool:
#        max-active: 20  #最大连接数，负值表示没有限制，默认8
#        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
#        max-idle: 8     #最大空闲连接，默认8
#        min-idle: 0     #最小空闲连接，默认0
logging:
  level:
    root: info

aliyun:
  sms:
    regionId : cn-shenzhen
    keyid: LTAI5tRb4YGPDqRjuCEazQkL
    keySecret: s0wh0QRH5izJQ79PPeyAEGgAK7Xmzp
    templateCode: SMS_217425770
    signName: 北京课时教育